### ISSUE TITLE
unique together can't be implemented (easily) 

### ISSUE THREAD

**Issue by csae8092** [acdh-oeaw/histogis#3]
trying:
```python
class Meta:
        ordering = ['id']
        unique_together = (("start_date", "end_date", "geom"),)
```
fails, because the value of `(("start_date", "end_date", "geom"),)` causes
> index row size 5328 exceeds maximum 2712

To fix this, I guess one would either 
* have to change somehow the index definition on SQL base, or
* add an additional field to TempSpatial storing some hash of `"start_date", "end_date", "geom"`

**Comment by zozlak** [comment]
Not sure about the Python part but on the database level `alter table meta add unique(start_date, end_date, st_envelope(geom));` should do the job (geometry can be very complicated while it's envelope has only 4 points and until you don't have really special geometries these points should still be unique).

**Comment by csae8092** [comment]
Because I'd like to avoid fiddling with Django's ORM I generate some kind of temporalized geo-hash and check its uniqueness.
