### ISSUE TITLE
improve performance / reduce memory consumption

### ISSUE THREAD

**Issue by csae8092** [acdh-oeaw/histogis#40]
looks like HistoGis consumes a lot of RAM; my best guess is this is related to some spatial queries and processing the results in order to construct some hierarchy of shapes on the fly; since this hierarchy is based purely on spatial lookups and not curated manually they are not always correct and can therefore be deprecated

**Comment by zozlak** [comment]
By the way - how it's technically done?
The fact that you notice high memory consumption would suggest it's done client side but if I'm right, the data is in the PostGIS database so I would rather expect such queries to generate load on the database side.
Anyway if the problematic features are valuable I can take a quick look - I have quite some experience in optimizing spatial queries.

**Comment by csae8092** [comment]
I suspect those methods
https://github.com/acdh-oeaw/histogis/blob/f2dbde116ef5b173021d4fa207f66f54f7b05e95/shps/models.py#L324
https://github.com/acdh-oeaw/histogis/blob/master/shps/models.py#L341
https://github.com/acdh-oeaw/histogis/blob/f2dbde116ef5b173021d4fa207f66f54f7b05e95/shps/models.py#L355

not sure how useful this is for you and as mentioned above, the results are sketchy anyhow and I'm not sure if anyone uses those features

**Comment by zozlak** [comment]
Huh, the tricky part is it's defined with the high level API giving us no insight on how the filtering is actually being done.
I guess you depend on some Django spatial extension/plugin/whatever here - can you post a link to its docs?

**Comment by csae8092** [comment]
https://docs.djangoproject.com/en/4.0/ref/contrib/gis/functions/
https://docs.djangoproject.com/en/4.0/ref/contrib/gis/geos/
https://docs.djangoproject.com/en/4.0/ref/contrib/gis/tutorial/#spatial-queries
